# Generated by Django 4.0.5 on 2022-07-01 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('adresse', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('availablecheck_in', models.DateTimeField(default=datetime.datetime(2022, 7, 1, 22, 39, 56, 344558))),
                ('is_published', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_main1', models.ImageField(blank=b'I01\n', upload_to='photos/%Y/%m/%d/')),
                ('photo_main2', models.ImageField(blank=b'I01\n', upload_to='photos/%Y/%m/%d/')),
                ('photo_main3', models.ImageField(blank=b'I01\n', upload_to='photos/%Y/%m/%d/')),
                ('photo_main4', models.ImageField(blank=b'I01\n', upload_to='photos/%Y/%m/%d/')),
                ('review', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
