# Generated by Django 4.0.5 on 2022-07-01 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Listings',
            name='availablecheck_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 0, 25, 10, 50023)),
        ),
        migrations.AlterField(
            model_name='Listings',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='photo_main'),
        ),
    ]
