# Generated by Django 4.0.5 on 2022-07-01 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_alter_listings_availablecheck_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 0, 27, 5, 828302)),
        ),
    ]
