# Generated by Django 4.0.5 on 2022-07-03 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0003_alter_listings_availablecheck_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion_add', models.CharField(max_length=200)),
                ('cars_add', models.CharField(max_length=200)),
                ('availablecheck_inadd', models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 2, 33, 918422))),
                ('availablecheck_outadd', models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 2, 33, 918422))),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='availablecheck_out',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 2, 33, 917417)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 2, 33, 917417)),
        ),
    ]
