# Generated by Django 4.0.5 on 2022-07-03 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0005_alter_admin_add_availablecheck_inadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_add',
            name='availablecheck_inadd',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 3, 48, 370743)),
        ),
        migrations.AlterField(
            model_name='admin_add',
            name='availablecheck_outadd',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 3, 48, 370743)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 3, 48, 369743)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_out',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 3, 48, 369743)),
        ),
    ]
