# Generated by Django 4.0.5 on 2022-07-03 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0006_alter_admin_add_availablecheck_inadd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='availablecheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availablecheck_inadd', models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 14, 9, 335161))),
                ('availablecheck_outadd', models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 14, 9, 335161))),
            ],
        ),
        migrations.CreateModel(
            name='cars_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_add', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='excursion_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion_add', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='admin_add',
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 14, 9, 318164)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_out',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 11, 14, 9, 318164)),
        ),
    ]
