# Generated by Django 4.0.5 on 2022-07-03 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0007_availablecheck_cars_add_excursion_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecheck',
            name='availablecheck_inadd',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 13, 9, 146098)),
        ),
        migrations.AlterField(
            model_name='availablecheck',
            name='availablecheck_outadd',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 13, 9, 146098)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 13, 9, 130097)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_out',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 13, 9, 130097)),
        ),
    ]
