# Generated by Django 4.0.5 on 2022-07-03 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0009_alter_availablecheck_availablecheck_inadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecheck',
            name='availablecheck_inadd',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 26, 40, 485327)),
        ),
        migrations.AlterField(
            model_name='availablecheck',
            name='availablecheck_outadd',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 26, 40, 485327)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 26, 40, 469327)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='availablecheck_out',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 26, 40, 469327)),
        ),
    ]
