# Generated by Django 4.0.5 on 2022-07-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserver',
            name='state',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='reserver',
            name='streetline_2',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
