# Generated by Django 4.0.5 on 2022-07-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0002_alter_reserver_state_alter_reserver_streetline_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserver',
            name='phone_cl',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
