# Generated by Django 4.0.5 on 2022-07-03 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reserver', '0005_rename_first_name_reserver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserver',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
