# Generated by Django 4.0.5 on 2022-07-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0006_alter_reserver_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserver',
            name='client',
        ),
    ]
